### ISSUE TITLE
AssertionError regarding shapes of user_embedding variable and user_features parameter

### ISSUE THREAD

**Issue by thisisandreeeee** [lyst/lightfm#108]
I'm trying to fit a very basic instance of LightFM

``` python
model = LightFM(loss='warp')
model = model.fit(df, user_features=user_features)
```

Where it can be noted that df.shape = (222113, 2269), and user_features.shape = (222113, 24). The model object is able to be fitted, but when I subsequently try to call the `auc_score` method, I get the following error.

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model = engine.fit(train, test, user_features=user_feat)
  File "/path/to/dir/lightfm-engine/engine.py", line 23, in fit
    train_auc = auc_score(model, train, num_threads=self.NUM_THREADS).mean()
  File "/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/evaluation.py", line 118, in auc_score
    num_threads=num_threads)
  File "/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/lightfm.py", line 649, in predict_rank
    item_features)
  File "/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/lightfm.py", line 235, in _construct_feature_matrices
    assert self.user_embeddings.shape[0] >= user_features.shape[1]
AssertionError
```

So I thought, maybe the shapes of the two sparse matrices are different but as it turns out:

``` python
model.user_embeddings.shape[0] = 24
user_features.shape[1] = 24
```

Not really sure what's wrong, because the boolean value of the assert statement should evaluate to True in this case.

**Comment by maciejkula** [comment]
You need to pass user_features to the predict call as well (or auc_score as
is the case here).

**Comment by thisisandreeeee** [comment]
Thanks for the quick reply @maciejkula, all is well now.

I have encountered a separate problem though. My user_features matrix is a scipy CSR matrix of type np.float64. If I'm not wrong this is being cast to a C double instead of a flt - and it seems that it is required:
```
/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model = engine.fit(train, test, user_features=user_features)
  File "/path/to/dir/lightfm-engine/engine.py", line 19, in fit
    train_auc = auc_score(model, train, user_features=user_features, num_threads=self.NUM_THREADS).mean()
  File "/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/evaluation.py", line 118, in auc_score
    num_threads=num_threads)
  File "/Users/me/miniconda3/envs/py2/lib/python2.7/site-packages/lightfm/lightfm.py", line 675, in predict_rank
    CSRMatrix(user_features),
  File "lightfm/_lightfm_fast_no_openmp.pyx", line 156, in lightfm._lightfm_fast_no_openmp.CSRMatrix.__init__ (lightfm/_lightfm_fast_no_openmp.c:2339)
ValueError: Buffer dtype mismatch, expected 'flt' but got 'double'
``` 
Is there some underlying piece of logic that automatically converts the np.float64 dtype to a double? I apologize for the many questions, just trying to figure things out. Thanks buddy

**Comment by maciejkula** [comment]
This is because your data is a `double` (`np.float64`), and it expects a `float`.

Arguably there should be a piece of code that does the casting automatically if needed. I'd be happy to accept a PR to that effect.

**Comment by dlmccaffrey** [comment]
How do you create the csr matrix to have float values then? I can only seem to get it to be np.float64.
