### ISSUE TITLE
Unable to import LightFM DataSets using Python 3.5

### ISSUE THREAD

**Issue by salman-bhai** [lyst/lightfm#136]
```
from lightfm.datasets import fetch_movielens
from lightfm import LightFM

#Fetch data and format it
data = fetch_movielens(min_rating=4.0)

#Print training and testing data
print(repr(data['train']))
print(repr(data['test']))
```

**The error I got for running this Python code was this:**
```
/home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Traceback (most recent call last):
  File "/home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/_lightfm_fast.py", line 3, in <module>
    from ._lightfm_fast_openmp import *  # NOQA
ImportError: /home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/_lightfm_fast_openmp.cpython-35m-x86_64-linux-gnu.so: undefined symbol: GOMP_parallel
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "recommendation_system.py", line 2, in <module>
    from lightfm.datasets import fetch_movielens
  File "/home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/__init__.py", line 1, in <module>
    from .lightfm import LightFM
  File "/home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/lightfm.py", line 7, in <module>
    from ._lightfm_fast import (CSRMatrix, FastLightFM,
  File "/home/salman/anaconda3/envs/tensorflow/lib/python3.5/site-packages/lightfm/_lightfm_fast.py", line 12, in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
ImportError: No module named 'lightfm._lightfm_fast_no_openmp'
````

**Comment by maciejkula** [comment]
How did you install LightFM? What directory are you running this code from?

**Comment by salman-bhai** [comment]
Oh wait does LightFM have to be downloaded in the same directory where I was running this code?

**Comment by maciejkula** [comment]
No. But doing so is one explanation for import problems.

**Comment by salman-bhai** [comment]
Alright let me try by putting it in the same directory! If it works out, I'll close this Issue, if not I'll get back to you anyways!

**Comment by maciejkula** [comment]
If your cloned lightfm code is in your import path but you installed into `site-packages`, you will have problems.

**Comment by maciejkula** [comment]
Any luck?
