### ISSUE TITLE
Install fails: UnicodeDecodeError and PermissionError 

### ISSUE THREAD

**Issue by snufflemate** [lyst/lightfm#282]
How can I get around this error?

C:\Users\Username\Documents\Code>pip install lightfm
Collecting lightfm
  Using cached lightfm-1.14.tar.gz
Requirement already up-to-date: numpy in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from lightfm)
Requirement already up-to-date: scipy>=0.17.0 in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from lightfm)
Requirement already up-to-date: requests in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from lightfm)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from requests->lightfm)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from requests->lightfm)
Requirement already up-to-date: certifi>=2017.4.17 in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from requests->lightfm)
Requirement already up-to-date: idna<2.7,>=2.5 in c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages (from requests->lightfm)
Installing collected packages: lightfm
  Running setup.py install for lightfm ... error
Exception:
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 142: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 142: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-build-sr9azq0l\\lightfm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-build-sr9azq0l\\lightfm'

last line: "process can't be used because it is used by another process"

**Comment by maciejkula** [comment]
Might be your error, nothing to do with LightFM:
https://github.com/pypa/pip/issues/4251

GitHub issue formatting tips, for formatting code blocks:
https://guides.github.com/features/mastering-markdown/
