### ISSUE TITLE
python lightfm ValueError: The user feature matrix specifies more features than there are estimated feature embeddings

### ISSUE THREAD

**Issue by limacher58** [lyst/lightfm#291]
I try to use lightfm v. 1.14 to build a hybrid recommender system.

I was able to put all my data in a sparse matrix with the following code:

```
db = DBConnector().getDBConnector()
data = pd.read_sql('call get_UserItemRating();', con=db)

rows = data.loc[data['userID'].idxmax()]['userID'] + 1
cols = data.loc[data['itemID'].idxmax()]['itemID'] + 1
mat = sp.lil_matrix((rows, cols), dtype=np.int32)
for index, row in data.iterrows():
    if row['rating'] >= 4:
        mat[row['userID'], row['itemID']] = row['rating']

train = mat.tocoo()

data = pd.read_sql('SELECT * FROM wine_grapes;', con=db)
db.close()
rows = data.loc[data['fk_Wine'].idxmax()]['fk_Wine'] + 1
cols = data.loc[data['fk_Grapes'].idxmax()]['fk_Grapes'] + 1
mat = sp.lil_matrix((rows, cols), dtype=np.int32)
for index, row in data.iterrows():
    mat[row['fk_Wine'],row['fk_Grapes']] = 1

item_features = mat.tocoo()

model = LightFM(loss='warp')
model.fit(train,
          item_features=item_features,
          epochs=20)
```
So far it looked good and only with the "train" i was able to get recommendations. But when I add the item_features I get the following error:

```
Traceback (most recent call last):
  File "/Users/dlimacher/PycharmProjects/deepWine/wineRecommender/WineRecommendation_lightfm.py", line 76, in <module>
    sample_recommendation(model, train, [1, 2, 3])
  File "/Users/dlimacher/PycharmProjects/deepWine/wineRecommender/WineRecommendation_lightfm.py", line 62, in sample_recommendation
    scores = model.predict(user_id, np.arange(n_items))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightfm/lightfm.py", line 713, in predict
    item_features)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightfm/lightfm.py", line 315, in _construct_feature_matrices
    item_features.shape[1]
ValueError: The user feature matrix specifies more features than there are estimated feature embeddings: 613 vs 1002.
```
First of all, it looks to me like the error message is wrong because it is about the item_features and not user_features.

But more important, I can't find my mistake. Can anybody help me with that?

**Comment by limacher58** [comment]
Problem should be solved in gitter comment, thanks a lot
