### ISSUE TITLE
Question :  ValueError: buffer source array is read-only

### ISSUE THREAD

**Issue by SanjiAp** [lyst/lightfm#404]
Hi,
I am able to run the same thing on different machine and on another machine, I am getting the following error:

**Traceback (most recent call last):
  File "lightfmTest.py", line 188, in <module>
    model.fit(trainCOO, epochs=300, num_threads=30)
  File "/usr/local/lib/python3.4/site-packages/lightfm-1.15-py3.4-linux-x86_64.egg/lightfm/lightfm.py", line 479, in fit
    verbose=verbose)
  File "/usr/local/lib/python3.4/site-packages/lightfm-1.15-py3.4-linux-x86_64.egg/lightfm/lightfm.py", line 576, in fit_partial
    self.loss)
  File "/usr/local/lib/python3.4/site-packages/lightfm-1.15-py3.4-linux-x86_64.egg/lightfm/lightfm.py", line 615, in _run_epoch
    self.random_state)
  File "lightfm/_lightfm_fast_openmp.pyx", line 793, in lightfm._lightfm_fast_openmp.fit_warp
  File "stringsource", line 646, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 347, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only**

Parameters and info : 
number of users : 727429
number of movies : 54000

loss function : warp
LR : 0.05

This is how I am building trainCOO

trainCOO = coo_matrix((train['ratingIndex'].astype(float), 
                   (train['uidIndex'].cat.codes, 
                    train['movieIndex'].cat.codes)),shape=(uidShape,movie_idShape))

**Comment by DPGrev** [comment]
When you run your code. Could you check your memory usage. It could be that you are running out of memory.

**Comment by DPGrev** [comment]
- Do you run it in the same pip/conda environment?
- If you try a sample of the dataset does the same error appear?

**Comment by maciejkula** [comment]
Can you prepare a snippet that I can run that reliably reproduces the issue?

**Comment by maciejkula** [comment]
Closing unless we can reproduce.

**Comment by arlopuhova** [comment]
@maciejkula Don't know if it makes sense to write about this issue almost a year later, but I'm having exactly the same issue now.

**Python versions**: 3.7.3, 2.7.13
**LightFM version**: 1.15
**Pandas versions**: 0.24.2  (Python2), 0.25.0  (Python3)
**scipy versions**: 0.17.1 (Python2), 1.3.1 (Python3)

**This runs ok:**
```
import lightfm
from scipy.sparse import coo_matrix
import pandas as pd

data = pd.DataFrame({'user': [1, 2, 3], 'item': [2, 3, 4], 'rating': [1, 0, 1]})
data.user = data.user.astype('category')
data.item = data.item.astype('category')
interactions = coo_matrix((data.rating.astype(float), (data.user.cat.codes, data.item.cat.codes)))
model = lightfm.LightFM()
model.fit(interactions)
```

**This fails with `ValueError: buffer source array is read-only`:**
```
data = pd.DataFrame({'user': list(range(100000)), 'item': list(range(100000)), 'rating': [1] * 100000})
data.user = data.user.astype('category')
data.item = data.item.astype('category')
interactions = coo_matrix((data.rating.astype(float), (data.user.cat.codes, data.item.cat.codes)))
model = lightfm.LightFM()
model.fit(interactions)
```

Full exception traceback:
```
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/lightfm/lightfm.py", line 479, in fit
    verbose=verbose)
  File "/usr/local/lib/python3.7/site-packages/lightfm/lightfm.py", line 576, in fit_partial
    self.loss)
  File "/usr/local/lib/python3.7/site-packages/lightfm/lightfm.py", line 657, in _run_epoch
    num_threads)
  File "lightfm/_lightfm_fast_no_openmp.pyx", line 696, in lightfm._lightfm_fast_no_openmp.fit_logistic
  File "stringsource", line 646, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 347, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

**This again runs ok (no `cat.codes`):**
```
data = pd.DataFrame({'user': list(range(100000)), 'item': list(range(100000)), 'rating': [1] * 100000})
interactions = coo_matrix((data.rating.astype(float), (data.user, data.item)))
model = lightfm.LightFM()
model.fit(interactions)
```

**Comment by ktleung2017** [comment]
@arlopuhova I ran into exactly the same problem as you. My LightFM version is 1.16. LightFM throws `ValueError: buffer source array is read-only` if I use `cat.codes` for user and item indices. 

I solved this by transforming `cat.codes` into a list object:

```
interactions = coo_matrix((
    [1] * len(df),
    (df['user_id'].cat.codes.tolist(), df['item_id'].cat.codes.tolist())
))
```
