### ISSUE TITLE
Not working  with python2.7 (ImportError: No module named _lightfm_fast_no_openmp)

### ISSUE THREAD

**Issue by 2mrdaya** [lyst/lightfm#410]
Thanks for opening an issue!

Please include as much detail as possible: what does your dataset look like, what hyperparameters you are using (and have you tried other ones?).

When including code snippets, make sure you use appropriate code formatting using backtics. Have a look at the markdown reference for details: https://guides.github.com/features/mastering-markdown/.

**Comment by 2mrdaya** [comment]
/home/daya/.local/lib/python2.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Traceback (most recent call last):
  File "recommend_catalogue.py", line 16, in <module>
    from lightfm import LightFM
  File "/home/daya/.local/lib/python2.7/site-packages/lightfm/__init__.py", line 4, in <module>
    from .lightfm import LightFM
  File "/home/daya/.local/lib/python2.7/site-packages/lightfm/lightfm.py", line 8, in <module>
    from ._lightfm_fast import (CSRMatrix, FastLightFM,
  File "/home/daya/.local/lib/python2.7/site-packages/lightfm/_lightfm_fast.py", line 12, in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
ImportError: No module named _lightfm_fast_no_openmp

**Comment by RILUCK** [comment]
How did you resolved it? @2mrdaya
