### ISSUE TITLE
Installation as suggested in the readme?

### ISSUE THREAD

**Issue by paoloRais** [lyst/lightfm#89]
I tried to modify some of the cython parts of the code, and I have issues at installing it afterwards.
I tried re-installing the original version of lightfm (just cloned from the repo) with the same procedure. The problem is when I run:
python setup.py cythonize

I obtain the error message:

running cythonize
Traceback (most recent call last):
  File "setup.py", line 152, in <module>
    ext_modules=define_extensions(use_openmp)
  File "/home/paolo/anaconda3/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/paolo/anaconda3/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/paolo/anaconda3/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 81, in run
    self.generate_pyx()
  File "setup.py", line 74, in generate_pyx
    fl.write(template.format(**template_params))
AttributeError: 'bytes' object has no attribute 'format'

I suspect there is a problem with the version of Python I am using (from a quick googling it appears that bytes have the attribute format starting in Python 3.5). Is python 3.5 really necessary?

**Comment by maciejkula** [comment]
Can you have a look at https://github.com/lyst/lightfm/pull/90 and see if that solves your problem?

**Comment by paoloRais** [comment]
Yes it does, thanks!

**Comment by maciejkula** [comment]
Merged, thanks for the report.
