### ISSUE TITLE
Error when building 'lightfm._lightfm_fast_no_openmp' extension

### ISSUE THREAD

**Issue by PhanDuc** [lyst/lightfm#97]
Hi, i install lightfm on my laptop Python enviroment : Windows 10, Python 3.4 64bit
But i had this error : 
```
E:\Download IDM\Compressed\lightfm-1.9.1\lightfm-1.9.1>python setup.py install
Compiling without OpenMP support.
running install
running bdist_egg
running egg_info
writing top-level names to lightfm.egg-info\top_level.txt
writing lightfm.egg-info\PKG-INFO
writing dependency_links to lightfm.egg-info\dependency_links.txt
writing requirements to lightfm.egg-info\requires.txt
reading manifest file 'lightfm.egg-info\SOURCES.txt'
writing manifest file 'lightfm.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.4
creating build\lib.win-amd64-3.4\lightfm
copying lightfm\evaluation.py -> build\lib.win-amd64-3.4\lightfm
copying lightfm\lightfm.py -> build\lib.win-amd64-3.4\lightfm
copying lightfm\_lightfm_fast.py -> build\lib.win-amd64-3.4\lightfm
copying lightfm\__init__.py -> build\lib.win-amd64-3.4\lightfm
creating build\lib.win-amd64-3.4\lightfm\datasets
copying lightfm\datasets\movielens.py -> build\lib.win-amd64-3.4\lightfm\datasets
copying lightfm\datasets\stackexchange.py -> build\lib.win-amd64-3.4\lightfm\datasets
copying lightfm\datasets\_common.py -> build\lib.win-amd64-3.4\lightfm\datasets
copying lightfm\datasets\__init__.py -> build\lib.win-amd64-3.4\lightfm\datasets
copying lightfm\_lightfm_fast_no_openmp.c -> build\lib.win-amd64-3.4\lightfm
copying lightfm\_lightfm_fast_openmp.c -> build\lib.win-amd64-3.4\lightfm
running build_ext
building 'lightfm._lightfm_fast_no_openmp' extension
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    ext_modules=define_extensions(use_openmp)
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install_lib.py", line 10, in run
    self.build()
  File "C:\Python34\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 66, in run
    _build_ext.run(self)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 178, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
    self.initialize()
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
    return unpatched['query_vcvarsall'](version, *args, **kwargs)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: ['path']
```
How i can fix that error, i tried this : https://github.com/lyst/lightfm/issues/29 
But still error.

**Comment by maciejkula** [comment]
You need working C compiler to install LightFM.

The easiest way to get this is to use [Miniconda](http://conda.pydata.org/miniconda.html) as your Python environment. Alternatively, you could install the Microsoft Visual C++ compiler.

**Comment by PhanDuc** [comment]
With Miniconda i had error : 
```
Error: Package missing in current win-64 channels:
  - lightfm-1.9.tar.gz
```

**Comment by maciejkula** [comment]
Use pip to install it.

**Comment by maciejkula** [comment]
You can use the https://github.com/lyst/lightfm/blob/master/appveyor.yml file for reference.

**Comment by PhanDuc** [comment]
Hi maciejkula, sorry for the late response
Now this is my error when i installed with Miniconda : 
```
C:\Users\palev>pip install -e F:\Miniconda3\envs\lightfm\Lib\lightfm-master\
Obtaining file:///F:/Miniconda3/envs/lightfm/Lib/lightfm-master
Requirement already satisfied (use --upgrade to upgrade): numpy in f:\miniconda3\envs\lightfm\lib\site-packages (from lightfm==1.9)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.17.0 in f:\miniconda3\envs\lightfm\lib\site-packages (from lightfm==1.9)
Requirement already satisfied (use --upgrade to upgrade): requests in f:\miniconda3\envs\lightfm\lib\site-packages (from lightfm==1.9)
Installing collected packages: lightfm
  Running setup.py develop for lightfm
    Complete output from command F:\Miniconda3\envs\lightfm\python.exe -c "import setuptools, tokenize;__file__='F:\\Miniconda3\\envs\\lightfm\\Lib\\lightfm-master\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    Compiling without OpenMP support.
    running develop
    running egg_info
    writing lightfm.egg-info\PKG-INFO
    writing dependency_links to lightfm.egg-info\dependency_links.txt
    writing top-level names to lightfm.egg-info\top_level.txt
    writing requirements to lightfm.egg-info\requires.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'lightfm.egg-info\SOURCES.txt'
    writing manifest file 'lightfm.egg-info\SOURCES.txt'
    running build_ext
    building 'lightfm._lightfm_fast_no_openmp' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "F:\Miniconda3\envs\lightfm\python.exe -c "import setuptools, tokenize;__file__='F:\\Miniconda3\\envs\\lightfm\\Lib\\lightfm-master\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in F:\Miniconda3\envs\lightfm\Lib\lightfm-master\
```

**Comment by maciejkula** [comment]
It looks like you still need the Microsoft C compiler. There are some pointer here: https://wiki.python.org/moin/WindowsCompilers

In general I strongly recommend developing on Linux.

**Comment by faresgh4** [comment]
Hey, i have the same problem on windows 8.1, i tries with anaconda but nothing works, can i please get some help !!!!
